baseURL = 'https://blog.baldbee.me/'
languageCode = 'en-us'
title = 'Sudhanshu Bhardwaj'
theme = 'paper'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  color = 'linen'
  twitter = '1337_sb'
  github = 'thesfb'
  customCSS = ["css/custom.css"]
  

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 10